openapi: 3.0.0
info:
  title: API de Usuarios
  version: 1.0.0
  description: Documentación de la API para gestionar usuarios.

servers:
  - url: http://localhost:3000
    description: Servidor local para desarrollo

paths:
  /api/user/getAllUsers:
    get:
      summary: Obtener todos los usuarios
      description: Obtiene una lista de todos los usuarios registrados en el sistema.
      tags:
        - Usuarios
      responses:
        '200':
          description: Lista de usuarios obtenida con éxito.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Error en el servidor.

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        password:
          type: string
